services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/gluetun:/gluetun # optional: caches server list
    ports:
      # qBittorrent WebUI (will route through VPN)
      - 8080:8080
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/qbittorrent:/config
      - ${DOWNLOAD_PATH}:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped
